### ISSUE TITLE
Links are marked as visited after history was wiped

### ISSUE THREAD

**Issue by reisub-de** [mozilla-mobile/focus-android#1600]
#322 is where this issue was discussed previously. There doesn't seem to be much action in the Chromium bug we filed. 
----

Platform:
- Android 7.1.2 LineageOs 14.1-201710010-NIGHTLY-piccolo
- Firefox Focus (Klar) version 2.2

To reproduce:
- visit any website which has a separate style for visited links (or the default style), e.g. https://gcc.gnu.org
- close Firefox Focus and wipe the history
- open Firefox Focus and visit the last domain
- all links visited in the previous session have the visited style applied

Expected behavior: links visited in the last session should be styled normally

Workaround: close Firefox Focus in the recent-app view

**Comment by reisub-de** [comment]
Could also reproduce this in the master branch

**Comment by pocmo** [comment]
Related: #1306, #1220, #990

**Comment by bbinto** [comment]
From another user.
Go to say the bbc news page 
- http://www.bbc.com/news/business
- Open some links from the page into new tabs and view them
- Clear the Firefox Focus cache at the end of session
- Start Firefox focus with the bbc news page - previously viewed links are now grayed out.

If you Stop Firefox Focus and clear the Android Cache, then everything is clean.

Tested on:
Android 7 on a Lenovo Tablet 4 8 plus
Android 5.1 OPPO R7S phone
Android 6 Motorola Moto G Gen 2

and seems to not have happened before 2.3

**Comment by liuche** [comment]
Copying over comments from #1392 and duping that bug to this one (there are some commits linked to #1392 though).

**Comment by Sdaswani** [comment]
this can move out to 4.1.

**Comment by bbinto** [comment]
Re-surfacing for triage after Focus release changes

**Comment by vesta0** [comment]
I believe this was fixed. Need QA to verify.

**Comment by doublez13** [comment]
Still valid on 7.0.13

Go to wiki.kernel.org
Tap the rt link (first link on the list)
Tap trash can
Go to wiki.kernel.org
rt link still appears purple

**Comment by sv-ohorvath** [comment]
I confirm it's still reproducing on 8.0.5, but only on webView. 
After links are visited, they appear as visited after:
- clearing history and going back to wiki.kernel.org or bbc.com/news
- not clearing history, close & reopen the browser, opening the page again (wiki.kernel.org or bbc.com/news).
devices: Samsung Galaxy S8 (Android 8.0), Huawei P9 Lite (Android 6.0)

**Comment by albell** [comment]
Confirmed happening on:
* Android version: 8.0.0
* Focus version: 7.0.13

This is deeply concerning it shows that my browsing history is in fact being stored somewhere locally (the Android cache?), and the whole promise of Focus is that sort of thing isn't supposed to happen. 

I just tested and private windows in Firefox don't have this issue. Focus should be more private than a regular FF private window, not less!  I've been waiting and waiting for this to get fixed. I was hoping the move to Gecko would resolve it. I know there are lots of issues, but as a user I would love to see this escalated. Thanks.

**Comment by vesta0** [comment]
@albell thanks for your feedback. This is a WebView only bug and does not happen in GeckoView (which is why you can't reproduce it in a Firefox private window). Focus version 7.0.13 is still on WebView but we are currently doing a slow roll out of GeckoView on Focus 8.0 so you will see this resolved soon. All the best!

**Comment by pocmo** [comment]
> This is deeply concerning it shows that my browsing history is in fact being stored somewhere locally (the Android cache?), and the whole promise of Focus is that sort of thing isn't supposed to happen.

And to clarify: The data about what links have been visited by WebView is kept in memory longer than we would like to. However it is not stored permanently. [WebView bug report](https://codereview.chromium.org/11886055).
