### ISSUE TITLE
Klar+GeckoView: Search results should be displayed in the selected language

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2412]
Build: Klar+GeckoView

Devices:
Xiaomi Mi Pad 2 (Android 5.1) - x86
HTC Desire 820 (Android 6.0.1) - arm

STR:
1. Change the preferred language from English to e.g. Deutsch.
2. Perform a search on Google/DuckDuck Go.

Expected result: The results are displayed in German, as it is on Focus.
Actual results: Search results are displayed in English.

**Comment by ekager** [comment]
See Issue #666 for WebView history. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1486552 for GV

**Comment by sv-ohorvath** [comment]
@ekager I'm still seeing the search result page in Romanian, instead of German/Spanish, on both Google and DuckDuckGo. On master and Nightly, with GV. System language is English, location is turned off.

**Comment by sv-ohorvath** [comment]
Still seeing the same result on today's Nightly (#323541226 GV 64.0.20181214004633).
![screenshot_2018-12-20-15-08-35](https://user-images.githubusercontent.com/4037709/50287057-034e0500-046a-11e9-8000-2eac9b8b91ef.png)

**Comment by cpeterso** [comment]
The GV API to change the locale landed in GV 63. I think Focus just needs to use the new API.

https://bugzilla.mozilla.org/show_bug.cgi?id=1486552

**Comment by vesta0** [comment]
@sv-ohorvath can we please verify that this has been fixed in 8.0.5?

**Comment by sv-ohorvath** [comment]
Still reproducing on Nightly 8.0.5 (#330111231 GV 64.0.2018.1214004633) (shouldn't the version number be updated?).

**Comment by ekager** [comment]
I asked the GV team about this and as of 1/17/19 this doesn't actually work because GV doesn't yet have multi-locale builds, although they are landing in MC soon.

**Comment by cpeterso** [comment]
Emily is correct. Here's the GV bug for multi-locale builds, which was fixed in GV 66. Focus 9.0 uses GV 65. I don't know when (or if) Focus will update to GV 66.

https://bugzilla.mozilla.org/show_bug.cgi?id=1496190
