### ISSUE TITLE
Notes Experiments page doesn't load

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/focus-android#2883]
### Steps to reproduce

Navigate to https://testpilot.firefox.com/experiments/notes

### Expected behavior

Page loads. 

### Actual behavior

Background and an image seems to load, but no other page content appears. 

Firefox Klar (stable from F-Droid) loads this with no issue, as does Fennec. Issue appears with default tracker blocklist as well as when disabling from main menu. 

![signal-attachment-2018-07-11-162643](https://user-images.githubusercontent.com/152493/42597749-d2e71544-8527-11e8-83d2-1ecc9ffa7029.png)

### Device information

* Android device: LG-H810, Android 5.1
* Focus version: 6.2 (Build #221921206 Emoji image of 'lizard' 62.0.20180709172241)

**Comment by bbinto** [comment]
Let's figure out the WHY, and discuss after what the next steps are.

**Comment by cpeterso** [comment]
Since this bug only happens with GeckoView and a portion of the page in the screenshot appears to be rendered, this problem might be related to [GeckoView rendering bug 1472356](https://bugzilla.mozilla.org/show_bug.cgi?id=1472356). We have a potential workaround (disabling SkiaGL on Android) in [Firefox bug 1468801](https://bugzilla.mozilla.org/show_bug.cgi?id=1468801).

**Comment by vesta0** [comment]
Can we verify that this has been fixed?

**Comment by sv-ohorvath** [comment]
Still reproducing on Nightly 8.0.4 & Release 8.0.5 on GeckoView.

**Comment by lobontiumira** [comment]
Verified as fixed on the 8.16.0 Focus build with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
