### ISSUE TITLE
Geckoview: video playback does not stop after going back to the launcher

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2927]
## Steps to reproduce
- Open Klar Geckoview, go to cnn, select a video to play
- When video is playing, press home button to exit to launcher

### Expected behavior
- The audio of video playback should not be playing
### Actual behavior
- The audio of video playback should not be playing

### Device information
Pixel 2, Android P
Master branch, commit 0e3cff5bc0a16e69dec5b841bdb0359d7aef2b41

**Comment by sholkayvishal** [comment]
There is a slight mistake in this issue, specifically in Actual Behavior. The following should be the correct actual behavior.

**Actual Behavior**
- The audio of video playback is still playing

**Comment by ekager** [comment]
Originally filed in #2209

**Comment by ekager** [comment]
May be solved by #2929

**Comment by ekager** [comment]
Hey @npark-mozilla can you confirm that this is now fixed on master and close this bug? Thanks!

**Comment by npark-mozilla** [comment]
hmm, it's still happening on the tip of the master, on both android P (pixel 2) and API 24 (moto 5).

**Comment by bbinto** [comment]
@npark-mozilla to confirm and close as appropriate

**Comment by ekager** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1483397

**Comment by ekager** [comment]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1483397 I learned that Fennec users wanted videos to continue playing in the background so this is working as intended. If we want to discuss stopping media when the app is backgrounded, we can open a new UX bug
