### ISSUE TITLE
The links sent to Focus behave unexpectedly

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3699]
## Steps to reproduce
1. In Focus, open the Settings menu and leave it open. 
2. Go to homescreen.
3. In Fennec, open a webpage and send it to Focus (from the 3 dots menu>Share>Focus).

### Expected behavior
The link opens in Focus, the new tab is brought to foreground.

### Actual behavior
 From Fennec, only an about:blank page is opened.
[Recording](https://drive.google.com/file/d/1rS-MF2cnrsO0rZ4F22wIub4dknsAVHIX/view?usp=sharing)

### Device information

* Android device: Samsung Galaxy S8 (Android 8.0), Samsung Galaxy Note 8 (Android 8.0)
Not reproducing on Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8.0).

* Focus version: 8.0.

**Comment by colintheshots** [comment]
This all seems to be working with the latest changes in Nightly, with the only exception that our browser shows up under the Gmail task. I believe this was fixed on Friday. When was this reproduced?

**Comment by sv-ohorvath** [comment]
Reproduced on the 2018-10-22 build too. Mostly on Android 8 & 9 devices, on an Android 7.1.1 just one tab, out of 3-4, was opened blank, the rest were ok. It might work ok on first try, but if you open more than 1 tab, it's very likely that you will see this.
[Recording #2](https://drive.google.com/file/d/10hS9RgZmnh9BamgRftVwwwke7Si4ZAj_/view?usp=sharing)
* The blank tab issue: can reproduce it with the Google news app too.
* Need to add that this is actually happening even without having the settings menu opened.

**Comment by sv-ohorvath** [comment]
Separated the Gmail issue to a new bug (#3713) and updated the description here.

**Comment by colintheshots** [comment]
This got fixed along with other intent-related bugs I fixed.

**Comment by sv-ohorvath** [comment]
Unfortunately, I can still reproduce this on a Pixel (Android 9) and a Samsung Galaxy S8 (Android 8.0), on today's Nightly build: 2018-10-29. Open 2 consecutive links from external apps.
 8.0 (build #323021211)

**Comment by ekager** [comment]
I think this may be fixed by #3795

**Comment by ekager** [comment]
Let us know if you can still reproduce on master tomorrow, @sv-ohorvath !

**Comment by sv-ohorvath** [comment]
Yes, it's fixed now on Master. Thanks!
