### ISSUE TITLE
Variable i gets reset to 0

### ISSUE THREAD

**Issue by zznidar** [mozilla-mobile/focus-android#4065]
JavaScript variable _i_ is reset to 0 after incrementing it by 1 on an xmlhttp.onprogress (onerror) event. If it is given a different name, _test_ for example, it is not reset to 0.

In Chrome 71.0.3578.99 for Android and Chrome, Firefox, Edge for Windows, variables are incremented regardless of the name.

**Demo:** 
https://zznidar.github.io/bugreports/Firefox%20Focus/Variable%20i%20gets%20reset%20to%200/

**Source code:**
index.html: https://raw.githubusercontent.com/zznidar/bugreports/master/Firefox%20Focus/Variable%20i%20gets%20reset%20to%200/index.html
runtime.js: https://raw.githubusercontent.com/zznidar/bugreports/master/Firefox%20Focus/Variable%20i%20gets%20reset%20to%200/runtime.js

## Steps to reproduce
1. Visit https://zznidar.github.io/bugreports/Firefox%20Focus/Variable%20i%20gets%20reset%20to%200/
2. Press the "Begin" button (Note: make sure JavaScript is enabled)
3. Wait a few seconds for an alert to appear
4. Press the "Begin" button again
5. Wait for another alert. Compare variables _i_ and _test_

### Expected behavior
Each variable, regardless of its name, should be incremented when variable++ is executed in js-code. Thus, both _i_ and _test_ should be increased by 1 each time an alert pops up.

### Actual behavior
Variable named _i_ is reset to 0 each cycle, hence the alert always outputs it as 1. Variable _test_ increments as expected.

### Device information

* Android device: pocophone f1, Android 8.1
* Focus version: 8.0.4

* Android device: Samsung Galaxy S8+, Android 8.0
* Focus version: 7.0.13

**Comment by colintheshots** [comment]
You're right. This is our fault and it's limited to WebView. It's caused by inserted JS polluting the namespace. We're moving to GeckoView soon, so we need to decide if we should fix this directly or simply change engines to fix it. Don't worry, we're on it.

https://github.com/mozilla-mobile/focus-android/blob/9827c021f0f0bacc3e1c68d007f6e15fac1e8467/app/src/main/java/org/mozilla/focus/webview/FocusWebViewClient.java#L100

**Comment by cpeterso** [comment]
```
 "for (i = 0; i < links.length; i++) {" +
```
Can this bug be fixed by declaring `let i` in the loop head? The current code is implicitly using a global variable `i`. Breaking web content could cause some pretty bad problems.

This typo would cause an exception if this code used JS `use strict` mode.

**Comment by niftylettuce** [comment]
I had the same issue, I was using `underscore.string` globally in window and the global `s` variable was getting reset to 0 instead of being an object with methods like `s.isBlank`.

Using latest version of Firefox Klar

Ref: https://github.com/epeli/underscore.string

**Comment by niftylettuce** [comment]
To clarify - I am still having this issue on latest versions.
