### ISSUE TITLE
The app crashes by tapping on 'Open and Erase' button when you are on Settings menu

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/focus-android#4342]
## Steps to reproduce
1. Open Firefox Focus;
2. Load a webpage;
3. Enter on the Settings menu;
4. Press the home button;
5. Pull down the notification tray and tap on the 'Erase and Open' button;

### Expected behavior
The initial screen of Focus is displayed, with the previous webpage deleted;

### Actual behavior
The app crashes when you 'Erase and Open' from the Settings Menu;

### Device information
* Android device: Google Pixel (Android Q), Samsung Galaxy S8 (Android 9);
* Focus version: 8.0.16 GV 69.0
*  [pushlog](https://github.com/mozilla-mobile/focus-android/files/3533572/crash.focus.txt)

**Comment by ebalazs-sv** [comment]
This is still reproducible on Focus 8.0.20 GV 71 on Pixel 2 (Android 9).
Also reproducible if in step 5, the 'Open' button is tapped.

**Comment by colintheshots** [comment]
It looks like this is the same Display Already Acquired issue that's been plaguing Fenix. We need to ensure that re-opening Focus doesn't create a new display for the same session.

**Comment by Diana-Rus** [comment]
Hi, issue is still reproducible with Firefox Focus 8.0.25 GV 71 with Google Pixel 3a (Android9).

**Comment by 13ABEL** [comment]
Hi, would it be possible for me to take the issue? I have investigated it and have a proposed solution

**Comment by 13ABEL** [comment]
@colintheshots Hey, just wanted to follow up to see if you're open for a quick look at a solution since this seems like a common issue? Changing the launch mode for the `MainActivity` from `singleTop` to `singleTask` should resolve the crash. I can provide a more detailed summary if necessary :)

**Comment by Diana-Rus** [comment]
Hi, Issue is still reproducible with Samsung Galaxy S9 (Android 8) on Focus 8.1.1 (Build #340941926) GV:74.0.1-20200403064753.

**Comment by Diana-Rus** [comment]
Hi, Issue is still reproducible with Sony Xperia Z5 (Android 7) on Focus 8.2.0 (Build #340992214) GV 75.0-20200403170909.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.3.0 (Build #341281936) GV 76.0.20200429185419 with Pixel 2 (Android 9).

**Comment by jgtoriginal** [comment]
The issue seems to happen only the second time onwards, on Samsung S8, Android 9.
Build 8.2.0 (Build #11 75.0.20200403170909)

![issue-4342](https://user-images.githubusercontent.com/1785392/81426014-fa2d0900-912e-11ea-9b91-9187f8ac3fe5.gif)

Here's the error output from logcat.

```2020-05-08 13:16:37.356 26947-26947/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-05-08 13:16:37.357 26947-26947/? E/Zygote: accessInfo : 1
2020-05-08 13:16:37.425 26947-26954/? E/lla.focus.debu: Unable to peek into adb socket due to error. Closing socket.: Connection reset by peer
2020-05-08 13:16:41.398 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load sqlite start
2020-05-08 13:16:41.408 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load sqlite done
2020-05-08 13:16:41.409 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load nss start
2020-05-08 13:16:41.409 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load nss done
2020-05-08 13:16:41.424 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Loaded libs in 15.180312ms total, 10ms(30ms) user, 0ms(10ms) system, 0(0) faults
2020-05-08 13:16:50.999 26947-26947/org.mozilla.focus.debug E/ViewRootImpl: sendUserActionEvent() returned.
2020-05-08 13:16:54.682 26947-26947/org.mozilla.focus.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 26947
    java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2315)
        at org.mozilla.geckoview.GeckoView.onAttachedToWindow(GeckoView.java:522)
        at android.view.View.dispatchAttachedToWindow(View.java:20018)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3589)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1876)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8499)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
        at android.view.Choreographer.doCallbacks(Choreographer.java:764)
        at android.view.Choreographer.doFrame(Choreographer.java:699)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)```

**Comment by jgtoriginal** [comment]
The issue seems to happen only the second time onwards, on Samsung S8, Android 9.
Build 8.2.0 (Build #11 75.0.20200403170909)

![20200508_131442](https://user-images.githubusercontent.com/1785392/81438267-dbd10880-9142-11ea-8206-c2e05bfe893f.gif)

Here's the error output from logcat.

```2020-05-08 13:16:37.356 26947-26947/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-05-08 13:16:37.357 26947-26947/? E/Zygote: accessInfo : 1
2020-05-08 13:16:37.425 26947-26954/? E/lla.focus.debu: Unable to peek into adb socket due to error. Closing socket.: Connection reset by peer
2020-05-08 13:16:41.398 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load sqlite start
2020-05-08 13:16:41.408 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load sqlite done
2020-05-08 13:16:41.409 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load nss start
2020-05-08 13:16:41.409 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Load nss done
2020-05-08 13:16:41.424 26947-27003/org.mozilla.focus.debug E/GeckoLibLoad: Loaded libs in 15.180312ms total, 10ms(30ms) user, 0ms(10ms) system, 0(0) faults
2020-05-08 13:16:50.999 26947-26947/org.mozilla.focus.debug E/ViewRootImpl: sendUserActionEvent() returned.
2020-05-08 13:16:54.682 26947-26947/org.mozilla.focus.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 26947
    java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2315)
        at org.mozilla.geckoview.GeckoView.onAttachedToWindow(GeckoView.java:522)
        at android.view.View.dispatchAttachedToWindow(View.java:20018)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3589)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1876)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8499)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
        at android.view.Choreographer.doCallbacks(Choreographer.java:764)
        at android.view.Choreographer.doFrame(Choreographer.java:699)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)```

**Comment by ebalazs-sv** [comment]
This issue is still reproducible on Focus 8.7.2 GV 80, from 8 /28, with Pixel 2 (Android 9).

**Comment by sv-ohorvath** [comment]
Still reproducing on Focus 8.8.4 (GV 81.0.2)

**Comment by sflorean** [comment]
Tested with Samsung Note 10 (Android 11) and Pixel (Android 10) on a dev build from master (#1186.0.1- 20210310152336) and after following the steps (Erase & Open), the app doesn't crash, instead the page opened is focused.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.14.0 with Pixel 2 (Android 9)

**Comment by lobontiumira** [comment]
I was not able to reproduce this crash on the 8.15.1 build with GV 88 on Samsung Galaxy Note 8 (Android 9), Xiaomi Mi 8 Lite (Android 9), nor on Google Pixel (Android 10).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.15.1 with Pixel 2 (Android 9).

**Comment by pocmo** [comment]
In the current version on `master` I do not see it crash, but the app opens and the tab is not removed. I'll investigate.

**Comment by pocmo** [comment]
This gets fixed when `launchMode="singleTask"` (like Fenix and RB), but that reintroduces bug #3624. Fenix doesn't have bug #3624 though. Maybe this is happening in Focus because it uses a separate activity for settings.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Focus 8.15.3 GV 88 with Huawei P9 Lite (Android 7).
