### ISSUE TITLE
Cannot add a new search engine

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#4817]
## Steps to reproduce
1. Go to settings - Search - Search engine and tap on "+ Add another search engine".
2. Insert valid credentials for the new search engine.
3. Tap on the "Save" button from the top-right corner.

### Expected behavior
The new search engine is added.

### Actual behavior
The "Server not found" error message is displayed.
I tried with: ecosia.com, imdb.com, reddit.com, wikipedia.com, youtube.com.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9)
* Focus version: 8.15.1, GV 88

![focus](https://user-images.githubusercontent.com/40694158/115516994-5da43e00-a28f-11eb-9801-1aab86909e63.png)

**Comment by lobontiumira** [comment]
Dupe of #4696

**Comment by lobontiumira** [comment]
Reproducible on 8.15.2 Focus build with Sony Xperia z5 Premium (Android 7.1.1).

**Comment by varanshukla** [comment]
It seems this issue has been fixed with #4761.

**Comment by lobontiumira** [comment]
This issue is not fixed on the 8.16.0 Focus build with Google Pixel (Android 10):

![Screenshot_20210531-113641](https://user-images.githubusercontent.com/40694158/120165791-99261680-c204-11eb-8e34-2aa91eedbb38.png)

**Comment by pocmo** [comment]
This was only fixed on `main`. The 8.x builds do not have a fix.
