### ISSUE TITLE
[Bug] After pressing on "Accept the Risk and Continue" in the notification "Secure Connection Failed", Firefox Focus marks untrusted by any reason HTTPS site connection as secure (Bugzilla 1714582)

### ISSUE THREAD

**Issue by Nickoriginal** [mozilla-mobile/focus-android#4921]
## Steps to reproduce
1. Open any untrusted site with HTTPS connection using Firefox Focus (for example, https://badssl.com/ and choose any "dangerous" link)
2. Skip notification "Secure Connection Failed" by tapping on "Accept the Risk and Continue"
3. Look at the security icon and status

### Expected behavior
Firefox Focus defines connection as unsecure even with security exception, like Firefox for Desktop
### Actual behavior
Firefox for Android defines connection and site's certificate as fully secure and misleads the user
### Device information

* Android device: Samsung Galaxy A20s (ARM64) with Android 10
* Focus version: 8.16.0 (Build #351481538 🦎 89.0-20210527174632)
## Video
https://user-images.githubusercontent.com/85299944/120746585-2ec4ed00-c508-11eb-9e69-45dbd4f12c36.mp4

**Comment by Nickoriginal** [comment]
Same issue for Fenix: [https://github.com/mozilla-mobile/fenix/issues/19799](url)

**Comment by Mugurell** [comment]
Opened a Bugzilla ticket for this issue since it seems to be a GeckoView issue - https://bugzilla.mozilla.org/show_bug.cgi?id=1714582

Keeping this ticket open to verify it later by QA.

**Comment by Nickoriginal** [comment]
Bugzilla [1714582](https://bugzilla.mozilla.org/show_bug.cgi?id=1714582) was fixed, but I cannot confirm it as fixed for Focus in the latest build [8.18.0-rc.1](https://github.com/mozilla-mobile/focus-android/releases/tag/v8.18.0).

**Comment by cadeyrn** [comment]
> Bugzilla 1714582 was fixed, but I cannot confirm it as fixed for Focus in the latest build 8.18.0-rc.1.

Bug 1714582 was fixed for Gecko 92, Focus 8.18 is based on Gecko 91.

**Comment by Nickoriginal** [comment]
I hope there is no different between acceptance of fixes in GV engine for Fenix and Focus... In Firefox Beta and Nightly, where Gecko is updated to 92, this bug is still present.
@cadeyrn, I know, that it shouldn't be said here about Fenix, but it is strange. It doesn't match behaviour, described by you.

**Comment by cadeyrn** [comment]
Well, I didn't describe any behaviour nor I verified that it works in Firefox 92. I only answered to the part that bug 1714582 was fixed. 😉 Maybe something else has to be done on the product side.

**Comment by Nickoriginal** [comment]
Not fixed in Focus 93.1.1.
<img src = https://user-images.githubusercontent.com/85299944/135510720-d450f5b6-fa8c-493b-b9e4-5a303d430257.jpg width = 35%>
@Mugurell, @cadeyrn it is fixed for you?

**Comment by Nickoriginal** [comment]
<img src=https://user-images.githubusercontent.com/85299944/150682781-67ee5ff9-aec6-4113-967f-637550a0084e.png width=50%>
Firefox Focus 96.2.0, Android 11

**Comment by Nickoriginal** [comment]
Reproducible in Focus 98.1.1
