### ISSUE TITLE
Adding a page on the home screen with ETP disabled will not open with it off

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/focus-android#5245]
## Steps to reproduce
1. Open any website;
2. Disable Enhanced Tracking Protection;
3. From the 3 dot menu select Add to Home screen;
4. Place the shortcut on the Home screen;
5. Close Focus;
6. Tap on the home screen shortcut from step 4.
### Expected behavior
The webpage should open in Focus with ETP disabled.
### Actual behavior
The webpage opens in Focus with ETP enabled.
### Device information
* Android device: Oppo Find X3 (Android 11), OnePlus 6T (Android 9)
* Focus version: 93.0.0

**Comment by brampitoyo** [comment]
@mcarare Yes. It makes sense to me that website shortcuts should open according to the ETP setting that has been stored in the Exceptions list.

**Comment by mcarare** [comment]
@brampitoyo, then should we remove the warning from the add to homes screen dialog?

**Comment by brampitoyo** [comment]
@mcarare I think the warning in the “Add to home screen” dialog should be kept, just so people don’t accidentally open sites without ETP.

**Comment by mcarare** [comment]
@brampitoyo Thank you for your feedback. Following the comments on this, I am going to close this issue, as there is nothing to fix.

**Comment by lobontiumira** [comment]
I will re-open this issue, since it is not clear to me what is the expected behaviour when adding a page with ETP off to the homescreen.
After discussing with Bram, this is the behaviour that we wanted:
* If you visited a page, disable ETP, and Add to Homescreen – that page should open with ETP off.
* If you visit the same page and re-enable ETP, then erase browsing history – Focus “remembers” the state of the ETP between sessions. When you open it from the homescreen, ETP should be on.

In this case, on 93.0.2, with Lenovo Tab M10 (Android 10), when adding a page with ETP disabled on the homescreen, that page is opened with ETP enabled when accessed through homescreen.
Not reproducible on the latest debug build from main from 9/14.

**Comment by mcarare** [comment]
@lobontiumira The state the page is opened in has nothing to do with the state of the ETP when the page was saved. It only follows the rule from the exception list.

**Comment by lobontiumira** [comment]
I've noticed a strange behavior now on the latest Focus Nightly from 11/22 (build 353260949 GV 96.0a1-20211120215911) with Samsung Galaxy Note 8 (Android 9):
1. Opened a page.
2. Disabled the ETP.
3. Added the page to the device's homescreen.
4. Cleared the history.
5. Opened the shortcut from the device's homescreen - the ETP is ON/enabled, even if the page is still listed in the Exceptions.
6. Opened Settings - then returned to the page - now the ETP is OFF/disabled.

Steps 5 & 6 can be seen in the short video below:

https://user-images.githubusercontent.com/40694158/142889305-317bdb37-2e5e-445f-b70e-9bbecd71793f.mp4

**Comment by delia-pop** [comment]
The behavior @lobontiumira described above is occurring on the 96.0.0-beta.1 (Build 353412232 GV 96.0-20211206194555) with Xiaomi Redmi Note 8T (Android 9) as well.

**Comment by ionutbedregeanu** [comment]
This should be fixed when https://github.com/mozilla-mobile/android-components/pull/11500 will be merged

**Comment by ionutbedregeanu** [comment]
> I've noticed a strange behavior now on the latest Focus Nightly from 11/22 (build 353260949 GV 96.0a1-20211120215911) with Samsung Galaxy Note 8 (Android 9):
> 
> 1. Opened a page.
> 2. Disabled the ETP.
> 3. Added the page to the device's homescreen.
> 4. Cleared the history.
> 5. Opened the shortcut from the device's homescreen - the ETP is ON/enabled, even if the page is still listed in the Exceptions.
> 6. Opened Settings - then returned to the page - now the ETP is OFF/disabled.
> 
> Steps 5 & 6 can be seen in the short video below:
> 
>  5245.mp4

This should be fixed when https://github.com/mozilla-mobile/android-components/pull/11500 will be merged

**Comment by lobontiumira** [comment]
Still reproducible on Beta 97.0.0-beta.1 with Samsung Galaxy Tab A6 (Android 5.1.1).

**Comment by delia-pop** [comment]
This can no longer be reproduced on Firefox Focus Nightly 98.0 (Build 360310515 🦎 98.0a1-20220130093554) with Google Pixel 6 (Android 12).

The shortcut from the device's homescreen opens with the ETP is OFF/disabled as expected.

https://user-images.githubusercontent.com/89388888/151779841-13c8f98b-f36b-4c4e-b073-aca8814260c4.mp4
