### ISSUE TITLE
Recent nightly builds did not upload to taskcluster

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#5752]
https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.focus-android.nightly.2021.10 – builds stop on the 28th: we're missing 29-31.

**Comment by rvandermeulen** [comment]
Fallout from #5712

**Comment by jonalmeida** [comment]
Should be fixed now with https://bugzilla.mozilla.org/show_bug.cgi?id=1738364 resolved a few hours ago.

**Comment by Archaeopteryx** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1738364 mentions `project/mobile/focus-android` while the change here uses `'project/focus-android`. Builds are [still failing](https://treeherder.mozilla.org/logviewer?job_id=356645439&repo=focus-android).

**Comment by Archaeopteryx** [comment]
This got fixed after bug 1738364 (got deployed later?).

**Comment by jonalmeida** [comment]
> This got fixed after [bug 1738364](https://bugzilla.mozilla.org/show_bug.cgi?id=1738364) (got deployed later?).

Yes, there was a deployment issue on cloudops side from what I followed. We were able to resolve this once the patch was deployed along with [this change](https://github.com/mozilla-mobile/focus-android/pull/5754).

I think we can close this now?

**Comment by jonalmeida** [comment]
Closing because nightly builds are back to normal.
