### ISSUE TITLE
[L10N] Incorrect linked text for the first carousel tip in Chinese

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5882]
## Steps to reproduce
1. Change the device language to Chinese.
2. Launch Firefox Focus
3. Observe that the 1st carousel tip.

### Expected behavior
The first character from the second string is also displayed as hyperlink.

### Actual behavior
The first character from the second string is not displayed as linked text.

### Device information
* Android device: all
* Focus version: 11/16 Focus Nightly 95.0 (build 353201509 GV 96.0a1-20211115093917
* Please see #5816

![chinese](https://user-images.githubusercontent.com/40694158/141995694-edd0df43-4d04-4e89-8c67-358c1ceba5a0.png)

**Comment by mcarare** [comment]
cc @Delphine  https://pontoon.mozilla.org/zh-CN/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=tip_fresh_look&string=230880.

**Comment by Delphine** [comment]
Fixed this like the Japanese error we had: #5816

**Comment by lobontiumira** [comment]
This is not fixed yet on the Focus Nightly build 95.0 (353231405 with GV 96.0a1-20211118034937) with Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
![Screenshot_20211119-140421](https://user-images.githubusercontent.com/40694158/142620819-dc82155d-d841-4305-b2a3-48d6a7bc6524.png)

**Comment by mcarare** [comment]
Please check it on the latest main or on the next Nightly.

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Firefox Focus Nightly 95.0 (build 353260949 GV 96.01-20211120215911) with Samsung Galaxy Note 8 (Android 9).

**Comment by delia-pop** [comment]
The issue is Still Present on the RC 95.1.0 (Build 353350147 GV 95.0-20211129150630) with LG G7 fit (Android 8.1.0).

**Comment by delia-pop** [comment]
This issue is also occurring on the 96.0.0-beta.1 (Build 353412232 GV 96.0-20211206194555) build with Xiaomi Redmi Note 8T (Android 9).

**Comment by Delphine** [comment]
@mcarare Any idea why this would still be an issue? thought I had fixed it the same way we dealt with #5816

**Comment by mcarare** [comment]
@Delphine It was not specified here which locale had the issue, but it seems it was wrong for both zh-TW and zh-CN. 
So the issue still reproduces for the one we had not fixed.
I made the change suggestion in [Pontoon](https://pontoon.mozilla.org/zh-TW/focus-for-android/mozilla-mobile/focus-android/app/src/main/res/values/strings.xml/?search=tip_fresh_look&string=230880).

**Comment by Delphine** [comment]
Makes sense, thanks
Approved translation
