### ISSUE TITLE
[Bug]:Refrences are not fully displayed when tappen on at at.wikimannia.org

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#6021]
## Steps to reproduce
1. Navigate to: https://at.wikimannia.org/Don_Alphonso.
2. Tap on a reference link ( a number inside [ ] ).
3. Observe the result.

### Expected behavior
The reference is fully displayed.
### Actual behavior
The reference is partially displayed (cropped).

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)
* Focus version: Firefox Focus 95.1.0 (353350148 -🦎95.0.20211129150630)

**Notes:**
1. Does not reproduce on the latest build of Firefox Nightly.
2. Does not reproduce using "Private mode".
3. Relevant screen recording attached:
![focus refrences](https://user-images.githubusercontent.com/75027050/145379223-b97e5be3-5fa7-4879-abad-04ad2ca7edf9.gif)

**Comment by RandomUser0815** [comment]
Thanks @softvision-raul-bucata

**Comment by RandomUser0815** [comment]
As for me the issues for the theguardian, wikimannia, Twitter and lots of other sites, that popups can not be accesed, has been fixed with Firefox focus 95.2.0

**Comment by ionutbedregeanu** [comment]
@softvision-raul-bucata Please let me know if you can still reproduce it

**Comment by lobontiumira** [comment]
This issue still reproduces on RC 95.2.0 with Google Pixel (Android 10).
It also reproduces on the 12/23 Focus Nightly.

https://user-images.githubusercontent.com/40694158/147246317-c6102f6a-ca32-4c47-99fd-15df56653eca.mp4
