### ISSUE TITLE
[L10N] The "Add to shortcuts" text is missing from the three-dot's menu in Dolnoserbski language

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6047]
## Steps to reproduce
1. Set the app to Dolnoserbski - Lower Sorbian.
2. Open a page.
3. Tap on the three-dot menu and observe the first option "Add to shortcuts".

### Expected behavior
The text of the option is visible.

### Actual behavior
The "Add to shortcuts" text is missing from the three-dot's menu in Dolnoserbski language.
The option is functional, tapping on the empty space creates a shortcut.
The "Remove shortcut" is visible.

### Device information
* Android device: Google Pixel (Android 10), Samsung Galaxy Note 8 (Android 9)
* Focus version: 96.0.0-beta.1

![Screenshot_20211213-105018](https://user-images.githubusercontent.com/40694158/145781847-eb6ecaa2-09b6-4426-b308-7ca70fd671c1.png)

**Comment by Delphine** [comment]
The string was actually saved empty in Pontoon, so I just fixed that. Should be fixed in the latest Nightly (tomorrow)
The fix should get into beta at the next cut-off date which I believe is 1/11

**Comment by milupo** [comment]
Thank you for opening and fixing the bug. I approved the translation on Pontoon.

**Comment by ionutbedregeanu** [comment]
I can't reproduce it anymore.
@lobontiumira Can you also confirm that was fixed and can be closed?

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly from 12/23 with Google Pixel (Android 10).
The issue still reproduces in Beta 96.0.0-beta.4.

**Comment by lobontiumira** [comment]
Verified as fixed also on Beta 101.0.0-beta.6 with Google Pixel (Android 10).
