### ISSUE TITLE
Setting to disable hiding the toolbar automatically

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#737]
From IRC: 

> Could Firefox Focus on Android also let disable hiding of that top bar like the normal Firefox for Android allows?

**Comment by pocmo** [comment]
We already have code for this (It's a custom tabs feature). We'd just need to expose a setting for it.

**Comment by pocmo** [comment]
We need to decide what to do with the auto-hiding "erase" button though. It's currently linked to the toolbar hiding code.

**Comment by brampitoyo** [comment]
Because the erase function is what makes Focus stand out from the rest of its competitors, the button should always appear on scroll up – so it’s available to access at all times – and never be auto-hidden.

**Comment by p0358** [comment]
Will this functionality be finally introduced?

**Comment by pocmo** [comment]
> Will this functionality be finally introduced?

Can you help us understand what problems you are having with the current state? :)

**Comment by p0358** [comment]
@pocmo Apart from it being simply annoying, imagine you are swiping around some map or zoomed image - annoying toolbar keeps appearing and disappearing, changing page's position underneath (if you drop finger when it's half-hidden). Such simple option thankfully present in regular Firefox for Android is livesaver here. I do not understand why is it taking so long to implement.

**Comment by brampitoyo** [comment]
@p0358 It sounds like what you want is a “Full-screen browsing” toggle, correct?

Pending feature prioritisation (ie. our team may or may not have the time to work on it), I agree on principle that this is a feature that will bring Focus to parity with Firefox for Android.

There’s a problem here, though, that will benefit from your feedback:

Let’s say that we’ve turned the “Full-screen browsing” toggle off. As a result, the Focus toolbar will always be shown when scrolling down a page.

In this scenario, should the erase button always be shown?

Here’s the problem:

* If we always show the erase button, it will cover a potentially important part of the screen, obscuring text or even buttons in the case of Google Maps.
* If we hide the erase button on scroll, the behaviour would be inconsistent with what you might expect: why is the erase button hidden on scroll, but the toolbar always shown?

I’d like to keep toolbar and erase button hide/show control to just one toggle, rather than have two separate toggles. It will keep our UI minimal, and gives us more time to build even more privacy-centric features.

Thanks for your help!

**Comment by p0358** [comment]
@brampitoyo Yes, this is how this toggle is called in Firefox for Android.

In my opinion, we should keep the current erase button behavior, that is it would hide on scroll-down, and show up again on scroll-up, while the only difference would be the toolbar being simply shown all the time, I do believe this is possible to accomplish and would be the best and easiest compromise - would not need to redesign any other scenarios, since no other behavior would change.

The only other option I see (considering the problems you mentioned) is an option to move the erase button to the menu (or a separate icon in toolbar to the left of the menu), but that would, on the other hand, be a rather major design change, so the first solution is probably much better way to go.

**Comment by p0358** [comment]
You're a joke, at least the part with moving page underneath should be fixed long time ago. Makes browsing maps and images overly annoying, and even normal pages when you slide up and down. I'm done with this browser as soon as I find some good alternative based on built-in WebKit that isn't Chrome...

**Comment by brampitoyo** [comment]
@p0358 You’d be pleased to know that we’ve taken your suggestion and decided to move the erase button up to the top app bar. It doesn’t solve your problem specifically, but it does go some way towards getting us there.
